/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    BulletList: typeof import('./src/components/BulletList/BulletList.vue')['default']
    ExportToolbar: typeof import('./src/components/ExportToolbar/ExportToolbar.vue')['default']
    FormattedText: typeof import('./src/components/FormattedText/FormattedText.vue')['default']
    ResumeEditorPanel: typeof import('./src/components/ResumeEditorPanel/ResumeEditorPanel.vue')['default']
    ResumePreview: typeof import('./src/components/ResumePreview/ResumePreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
